name: ep-stack

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sampledb
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: your_jwt_secret_key_2025_used_for_securing_jwt
    ports:
      - "8080:8080"