spring.application.name=JPAEx1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/DemoDB
spring.datasource.username=root
spring.datasource.password=password